### ISSUE TITLE
Add Makefile

### ISSUE THREAD

**Issue by Taegeune** [Taegeune/Hello#1]
We need a Makefile to easy build.
i find your bug. 
because of you are school name

**Comment by Taegeune** [comment]
이슈이슈이슈 핫이슈 헤이! 
머리부터 발끝까지 핫이슈!

**Comment by ByeonHarin** [comment]
내모든것 하나하나 핫이슈

**Comment by Taegeune** [comment]
모두다 take control~~~~~~~

**Comment by Taegeune** [comment]
난항상 핫잇 하잇 핫잇 하잇 하하하핳하하하잇슈!

**Comment by ParkJaeHwan** [comment]
머리부터 발끝까지 다 사랑스러워
